### ISSUE TITLE
an Error in Pandas

### ISSUE THREAD

**Issue by naaktslaktauge** [jfloff/pywFM#22]
Hi.
I tried your sample code, then an error occurred in 
`"model = fm.run(features[:5], target[:5] , features[5:], target[5:])".`
Then, it says 
`"EmptyDataError: No columns to parse from file".`

Could you tell me how to solve this problem??

**Comment by naaktslaktauge** [comment]
My Python's version is 3.6.1.

**Comment by jfloff** [comment]
Which OS are you using?

**Comment by ryancheunggit** [comment]
I got a similar error message on MacOS, in my case, it seems to have something to do with `rlog` I set `rlog = False` and it works.

**Comment by naaktslaktauge** [comment]
I used `export LIBFM_PATH=/home/libfm/bin/`
instead of `export LIBFM_PATH=/home/libfm/bin`,
then, it worked! It was my easy mistake, I'm sorry.

**Comment by jfloff** [comment]
@naaktslaktauge Fixed that! Thank you! 👍 

@ryancheunggit could you give more information about that error? Were you using the default example or your own dataset?

**Comment by ryancheunggit** [comment]
Sorry, I couldn't reproduce the error anymore. It all works well now.

**Comment by jfloff** [comment]
Ok :) Feel free to reopen if you notice that again. Cheers!
